name=PLC_FX
version=1.0.0
author=Fernando Guillermo Oviedo
maintainer=TuNombre <oviedofernando71@gmail.com>
sentence=Libreria para comunicacion con PLC Mitsubishi FX1N mediante ESP32.
paragraph=Permite leer y escribir bits (X, Y, M, T) y registros de datos (D) usando el protocolo de programacion FX.
category=Communication
url=
architectures=esp32,avr